#!/bin/bash
#SBATCH --job-name=train1
#SBATCH --nodes=1 --ntasks=20
#SBATCH --gpus=1
#SBATCH --mem=48GB
#SBATCH --time=48:00:00
#SBATCH --output=./train1.out
#SBATCH --error=./train1.err
conda activate mhcflurry
python ./src/peptide_env.py --good_coef 0.01 --pretrain_iter 2000 --anneal_nomod_step 0 --allow_imm_rew 0 --clip 0.2 --gamma 0.9 --sample_rate 0.0 --num_envs 30 --stop_criteria 0.75 --reward_type game --mod_neg_penalty -1.0 --mod_pos_penalty 1.0 --n_steps 128 --no_mod_penalty -0.9 --path ./results/ --allele_hidden_dim 128 --allele_latent_dim 48 --allele_kmer 3 --embed_allele FC --peptide_latent_dim 48 --ent_coef 0.01 --rate 1
